### PR TITLE
 Support for applying template to existing project

### LINKED ISSUE #157: Apply template to existing Projects
Provide an API for applying this template to existing projects. This will use rails `app:template` command

Cd to an existing project and Run.
```
rails app:template LOCATION=https://raw.githubusercontent.com/excid3/jumpstart/master/template.rb
```

### PR DESCRIPTION
**Pull request by gathuku**
closes #157

### CODE REVIEW

**Comment by andyw8** [comment]
> Gem duplicate issues in case you apply to a project which already has this template gem present.

I think this should be resolved by a49f4f29f11cee913aa19c9f5b718a5b79a85506 ?

**Comment by andyw8** [comment]
I think this would be fragile to run on an existing project, since there could be big variations in the existing code structure. Perhaps one approach could be to have an `-i` (`--interactive`) option which could prompt before each step to either to run it or skip it?

**Comment by gathuku** [comment]
@andyw8  that's true, the initial idea was to apply to a newly created project https://github.com/excid3/jumpstart/issues/157#issuecomment-947144028
But we can't escape the reality someone might want to apply in an old project.

**Comment by excid3** [comment]
I think you're both right on applying this to existing projects.

**Pull request closed without merging**
