### PR TITLE
add password to new user page

### PR DESCRIPTION
**Pull request by pconley**
I noticed that the administrate add new user page does not actually allow the creation of a new user in the generated app because devise requires a password for creation... so, I propose these modifications to allow the actual creation of a new user.

### CODE REVIEW

**Comment by excid3** [comment]
@pconley you read my mind. 👍 Was just thinking about adding this.

One thing I think we could do to simplify this is to modify the UserDashboard instead to clean up the form. This way you wouldn't have to modify the params, etc.

Want to take a look at that and see if it cleans up things?

**Comment by pconley** [comment]
@excid3 Yeah... I see what you mean.  Good point.  I will take a look at that in a day or so.

**Comment by excid3** [comment]
👍 Let me know if you need any thing.

**Comment by pconley** [comment]
Closing this PR after brief experiment with the UserDashboard which seems to works and is a much easier way to make this change.

**Pull request closed without merging**
