### PR TITLE
Migrate jumpstart to Bootstrap 5.0.0.alpha3

### PR DESCRIPTION
**Pull request by stevenbuccini**
This PR attempts to migrate the current Jumpstart template to Bootstrap `5.0.0.alpha3`. I say "attempts" because there are a lot of changes and I'm sure I missed some things.

A high level summary:
- Update the template file to generate a Gemfile that points at the most recent Bootstrap release
- Drop `devise-bootstrapped` gem; bring those views within the project itself
- Implement changes for `alpha1` and `alpha2` releases (`alpha3` did not appear to have any changes that needed to be implemented)

@excid3, this PR is currently pointed at `master`. As previously discussed, we'd like to set up a `bootstrap5` release branch until Bootstrap 5 is formally released but I don't think I have the permissions to create that branch within your repo myself. Once you do that, we can swap the base branch over.

### CODE REVIEW

**Comment by stevenbuccini** [comment]
Partially resolves #116

**Comment by excid3** [comment]
Awesome, thanks @stevenbuccini!

I just created the `bootstrap5` branch for you https://github.com/excid3/jumpstart/tree/bootstrap5

**Comment by stevenbuccini** [comment]
Thanks! I've changed the base branch for this PR, so everything should be set up correctly now.

**Comment by excid3** [comment]
Perfect! I've went ahead and merged this and we can continue updating the bootstrap5 branch as needed. Then we'll merge into master when the final or an RC version comes out. 👍

**Comment by excid3** [comment]
Beta 1 is out! https://blog.getbootstrap.com/2020/12/07/bootstrap-5-beta-1/

**Pull request merged**
